// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a95e295d-0574-4d5e-baf1-48212b59ebd5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NndfK6oQ6",
    "aws_user_pools_web_client_id": "7vb8bkv8e6gfrvibda0d1ao0rk"
};


export default awsmobile;
